/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjeKodlar;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class ceza_ekle extends javax.swing.JFrame {

    /**
     * Creates new form ceza_ekle
     */
    public ceza_ekle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ceza_tip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ceza_tarih = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ceza_yer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kisi_tc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        plaka_no = new javax.swing.JTextField();
        eklebuton = new javax.swing.JButton();
        temizle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ceza tip id'sini girin:");

        jButton1.setText("Ceza tip idleri ve özellikleri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ceza_tip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceza_tipActionPerformed(evt);
            }
        });

        jLabel2.setText("Ceza tarihi ( \"gg/aa/yyyy \" ):");

        jLabel3.setText("Ceza yeri:");

        ceza_yer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceza_yerActionPerformed(evt);
            }
        });

        jLabel4.setText("Ceza uygulanacak kişinin T.C. no:");

        jLabel5.setText("Plaka no (örnek:\"34BBF965\" ):");

        eklebuton.setText("Cezayı Ekle");
        eklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklebutonActionPerformed(evt);
            }
        });

        temizle.setText("Temizle");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eklebuton, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addComponent(ceza_tarih, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ceza_tip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(ceza_yer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kisi_tc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plaka_no, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ceza_tip, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceza_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ceza_yer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kisi_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plaka_no, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(eklebuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new tablolu();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ceza_tipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceza_tipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceza_tipActionPerformed

    private void ceza_yerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceza_yerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceza_yerActionPerformed

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed
        // TODO add your handling code here:
        ceza_tip.setText("");
        ceza_tarih.setText("");
        ceza_yer.setText("");
        kisi_tc.setText("");
        plaka_no.setText("");
    }//GEN-LAST:event_temizleActionPerformed

    private void eklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklebutonActionPerformed
        // TODO add your handling code here:
        String user,pass;
        user="postgres";
        pass="1234";  
        try{
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/proje",user,pass);
            
            String c_tip=ceza_tip.getText();
            int cint=Integer.parseInt(c_tip);  
            String c_tarih = ceza_tarih.getText();
            String c_yer = ceza_yer.getText();
            String k_tc =kisi_tc.getText();
            long tcc=Long.parseLong(k_tc);
            String p_no= plaka_no.getText();
            
                String query1 = " insert into ceza_kaydi ( ceza_tipi, ceza_tarihi, ceza_adres, uyg_kisi_tc,uyg_plaka_no)"
        + " values ( ?, ?, ?, ?,?)";
                
            
                String query = " insert into ceza_kaydi ( ceza_tipi, ceza_tarihi, ceza_adres, uyg_kisi_tc)"
        + " values ( ?, ?, ?, ?)";
            
            try {
                //plakaya ceza yazılmaması gerekirken plaka kutucuğu doldurulursa bu değeri sıfırlama
                String sorgu= "select uygulama_tipi from ihlal where ceza_tipi_id ="+c_tip;
                Statement s5 = conn.createStatement();
		ResultSet r2 = s5.executeQuery(sorgu);
                
                if(r2.next()){
                    int uygulanma = r2.getInt(1);
                    if(uygulanma==1 && p_no.length()!=0){
                        p_no="";
                    }
                }
                s5.close();
            }catch(SQLException | NumberFormatException e){
                System.out.println("hata:"+e.getMessage());
            }  

            if(p_no.length()!=0){
                query=query1;
            }
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            if(p_no.length()!=0){
                preparedStmt.setString(5, p_no);
            }
            
            //bu satırı ekledi
            DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            try {
                java.util.Date tarih = format.parse(c_tarih);
                java.sql.Date tarihSql = new java.sql.Date(tarih.getTime());
                
                preparedStmt.setInt (1, cint);
                preparedStmt.setDate   (2, tarihSql);
                preparedStmt.setString(3, c_yer);
                preparedStmt.setLong(4, tcc);
            
                ResultSet rs =preparedStmt.executeQuery();
                preparedStmt.close();
            } catch (ParseException ex) {
                Logger.getLogger(ceza_ekle.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Tarih istenen formatta değil!!");
               
            }
            
            conn.close();
        }catch(SQLException | NumberFormatException e){
            System.out.println("hata:"+e.getMessage());
            String dogru="Sorgudan hiç bir sonuç dönmedi.";
            if(dogru.compareTo(e.getMessage())==0){
                JOptionPane.showMessageDialog(this, "              Ceza Girişi Başarılı!"+
                        "\nİlgili kişilerin ceza puanı ve borcu arttırılmıştır");
            }else{
                JOptionPane.showMessageDialog(this, "          Lütfen bilgileri doğru formatta girdiğinizden emin olunuz.\n"
                +"İp uçları:  T.C. no, Ceza tip id ve Plaka no kayıtlarımızda bulunuyor olmalı\n"+
                        "                          ve T.C. no 11 haneli olmalıdır.");
            }
            
        }
        
    }//GEN-LAST:event_eklebutonActionPerformed

    //public static void insert()throws SQLException, IOException{
        
    //}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ceza_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ceza_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ceza_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ceza_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ceza_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ceza_tarih;
    private javax.swing.JTextField ceza_tip;
    private javax.swing.JTextField ceza_yer;
    private javax.swing.JButton eklebuton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField kisi_tc;
    private javax.swing.JTextField plaka_no;
    private javax.swing.JButton temizle;
    // End of variables declaration//GEN-END:variables
}
